// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCplCg1TdGF0RXZlbnRUeXBlEhMKD1NU",
            "QVRfRVZFTlRfTk9ORRAAEhAKDERBTUFHRV9UQUtFThABEgoKBkhFQUxFRBAC",
            "Eg0KCUlURU1fVVNFRBADEhIKDk9YWUdFTl9DSEFOR0VEEAQqNAoKT2JqZWN0",
            "VHlwZRISCg5PQkpFQ1RfSURfTk9ORRAAEggKBFRPT0wQARIICgRJVEVNEAIq",
            "RQoISXRlbVR5cGUSCAoETk9ORRAAEggKBFdPT0QQZBIJCgVTVE9ORRBlEgwK",
            "CElST05fT1JFEGYSDAoIR09MRF9PUkUQZyo/CghUb29sVHlwZRISCg5UT09M",
            "X1RZUEVfTk9ORRAAEgcKA0FYRRBkEgsKB1BJQ0tBWEUQZRIJCgVEUklMTBBm",
            "KkkKCUl0ZW1TdGF0ZRITCg9JVEVNX1NUQVRFX05PTkUQABINCglPTl9HUk9V",
            "TkQQARIKCgZJTl9BSVIQAhIMCghFUVVJUFBFRBADKl4KDERhbWFnZVNvdXJj",
            "ZRIWChJEQU1BR0VfU09VUkNFX05PTkUQABIPCgtTVUZGT0NBVElPThABEhEK",
            "DUVOVklST05NRU5UQUwQAhISCg5NT05TVEVSX0FUVEFDSxADKkIKCkhlYWxT",
            "b3VyY2USFAoQSEVBTF9TT1VSQ0VfTk9ORRAAEg0KCVJFU1RfQVJFQRABEg8K",
            "C01FRElDQUxfS0lUEAIqeAoQT3h5Z2VuQ2hhbmdlVHlwZRIWChJPWFlHRU5f",
            "Q0hBTkdFX05PTkUQABITCg9DT05TVU1FX05BVFVSQUwQARITCg9DT05TVU1F",
            "X1JVTk5JTkcQAhIQCgxSRVNUT1JFX1RBTksQAxIQCgxSRVNUT1JFX0FSRUEQ",
            "BGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.StatEventType), typeof(global::Protocol.ObjectType), typeof(global::Protocol.ItemType), typeof(global::Protocol.ToolType), typeof(global::Protocol.ItemState), typeof(global::Protocol.DamageSource), typeof(global::Protocol.HealSource), typeof(global::Protocol.OxygenChangeType), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// ==================== 플레이어 스탯 이벤트 타입 ====================
  /// </summary>
  public enum StatEventType {
    [pbr::OriginalName("STAT_EVENT_NONE")] StatEventNone = 0,
    [pbr::OriginalName("DAMAGE_TAKEN")] DamageTaken = 1,
    [pbr::OriginalName("HEALED")] Healed = 2,
    [pbr::OriginalName("ITEM_USED")] ItemUsed = 3,
    [pbr::OriginalName("OXYGEN_CHANGED")] OxygenChanged = 4,
  }

  public enum ObjectType {
    [pbr::OriginalName("OBJECT_ID_NONE")] ObjectIdNone = 0,
    /// <summary>
    /// 도구
    /// </summary>
    [pbr::OriginalName("TOOL")] Tool = 1,
    /// <summary>
    /// 광석
    /// </summary>
    [pbr::OriginalName("ITEM")] Item = 2,
  }

  public enum ItemType {
    [pbr::OriginalName("NONE")] None = 0,
    /// <summary>
    /// 나무
    /// </summary>
    [pbr::OriginalName("WOOD")] Wood = 100,
    /// <summary>
    /// 돌
    /// </summary>
    [pbr::OriginalName("STONE")] Stone = 101,
    /// <summary>
    /// 철광석
    /// </summary>
    [pbr::OriginalName("IRON_ORE")] IronOre = 102,
    /// <summary>
    /// 금광석
    /// </summary>
    [pbr::OriginalName("GOLD_ORE")] GoldOre = 103,
  }

  /// <summary>
  /// ==================== 도구 타입 ====================
  /// </summary>
  public enum ToolType {
    [pbr::OriginalName("TOOL_TYPE_NONE")] None = 0,
    /// <summary>
    /// 도끼 - 나무 채집
    /// </summary>
    [pbr::OriginalName("AXE")] Axe = 100,
    /// <summary>
    /// 곡괭이 - 돌/광석 채집
    /// </summary>
    [pbr::OriginalName("PICKAXE")] Pickaxe = 101,
    /// <summary>
    /// 드릴 - 등급 높은 광석 채집
    /// </summary>
    [pbr::OriginalName("DRILL")] Drill = 102,
  }

  /// <summary>
  /// ==================== 아이템/도구 상태 ====================
  /// </summary>
  public enum ItemState {
    [pbr::OriginalName("ITEM_STATE_NONE")] None = 0,
    /// <summary>
    /// 바닥에 떨어진 상태
    /// </summary>
    [pbr::OriginalName("ON_GROUND")] OnGround = 1,
    /// <summary>
    /// 공중에 떠있는 상태 (던져진 직후)
    /// </summary>
    [pbr::OriginalName("IN_AIR")] InAir = 2,
    /// <summary>
    /// 플레이어가 장착한 상태
    /// </summary>
    [pbr::OriginalName("EQUIPPED")] Equipped = 3,
  }

  /// <summary>
  /// ==================== 데미지 원인 ====================
  /// </summary>
  public enum DamageSource {
    [pbr::OriginalName("DAMAGE_SOURCE_NONE")] None = 0,
    /// <summary>
    /// 산소 부족
    /// </summary>
    [pbr::OriginalName("SUFFOCATION")] Suffocation = 1,
    /// <summary>
    /// 환경 (가시, 함정)
    /// </summary>
    [pbr::OriginalName("ENVIRONMENTAL")] Environmental = 2,
    /// <summary>
    /// 몬스터 공격
    /// </summary>
    [pbr::OriginalName("MONSTER_ATTACK")] MonsterAttack = 3,
  }

  /// <summary>
  /// ==================== 회복 원인 ====================
  /// </summary>
  public enum HealSource {
    [pbr::OriginalName("HEAL_SOURCE_NONE")] None = 0,
    [pbr::OriginalName("REST_AREA")] RestArea = 1,
    [pbr::OriginalName("MEDICAL_KIT")] MedicalKit = 2,
  }

  /// <summary>
  /// ==================== 산소 변화 타입 ====================
  /// </summary>
  public enum OxygenChangeType {
    [pbr::OriginalName("OXYGEN_CHANGE_NONE")] OxygenChangeNone = 0,
    /// <summary>
    /// 자연 소모
    /// </summary>
    [pbr::OriginalName("CONSUME_NATURAL")] ConsumeNatural = 1,
    /// <summary>
    /// 달리기
    /// </summary>
    [pbr::OriginalName("CONSUME_RUNNING")] ConsumeRunning = 2,
    /// <summary>
    /// 산소통 사용
    /// </summary>
    [pbr::OriginalName("RESTORE_TANK")] RestoreTank = 3,
    /// <summary>
    /// 안전 구역
    /// </summary>
    [pbr::OriginalName("RESTORE_AREA")] RestoreArea = 4,
  }

  #endregion

}

#endregion Designer generated code
